// Generated by CoffeeScript 1.9.1
var app, kraken, options, port;

app = require('express')();

kraken = require('kraken-js');

options = require('./lib/spec')(app);

port = process.env.PORT || 8000;

app.use(kraken(options));

app.listen(port, function() {
  return console.log('fire up~ visit : http://localhost:' + port);
});
