// Generated by CoffeeScript 1.9.1
var path;

path = require('path');

module.exports = function(app) {
  return {
    onconfig: function(config, next) {
      return next(null, config);
    }
  };
};
